# Config
# ========================================================================================

# URL setting - Only set this when using GitHub Pages
url: https://cor5in.github.io

# General settings
# ---------------------------------------------------------------------------------------
lang: en
title: Corbin's Tech Journey
description: >
  Personal blog of Corbin Kim, a Telecom Software Engineer specializing in Open RAN, 
  AI-RAN, and LLM for RAN technologies. Sharing insights on next-generation wireless networks.

tagline: Telecom Software Engineer
keywords: [Open RAN, AI-RAN, LLM, RAN optimization, 5G, 6G, telecom, wireless networks, artificial intelligence, machine learning]
logo: /assets/img/logo.png

# Author information
author:
  name: Geon Kim
  email: cor5inkim@gmail.com

# Sidebar menu
menu:
  - title: Blog
    url: /blog/
  - title: Projects
    url: /projects/
  - title: CV
    url: /resume/
  - title: Documentation
    url: /docs/

# Footer links
legal:
  - title: LICENSE
    url: /LICENSE/
  - title: NOTICE
    url: /NOTICE/
  - title: CHANGELOG
    url: /CHANGELOG/

# This text will appear in a `<small>` tag in the footer of every page.
copyright: © 2024. All rights reserved.

# Jekyll build settings
# ---------------------------------------------------------------------------------------

# Remote theme setting for GitHub Pages - This is the key!
remote_theme: hydecorp/hydejack@v9

# For local development, comment out the above line and use this instead:
# theme: jekyll-theme-hydejack

# Posts settings (for _posts folder)
# ---------------------------------------------------------------------------------------

# Posts permalink format - Standard Jekyll blog structure
permalink: /blog/:year/:month/:day/:title/

# Pagination settings (required when using blog layout)
paginate: 10
paginate_path: /blog/:num/

# Markdown engine settings
markdown: kramdown
highlighter: rouge

# kramdown settings
kramdown:
  math_engine: mathjax
  math_engine_opts: {}
  footnote_backlink: '&#x21a9;&#xfe0e;'

# Customization
# ----------------------------------------------------------------------------------------
accent_image: /assets/img/sidebar-bg.jpg
accent_color: rgb(79,177,186)
theme_color: rgb(25,55,71)

# Collections settings
# ----------------------------------------------------------------------------------------
collections:
  featured_categories:
    permalink: /:name/
    output: true
  featured_tags:
    permalink: /tag-:name/
    output: true
  projects:
    permalink: /projects/:path/
    output: true

# Front matter defaults
# ---------------------------------------------------------------------------------------
defaults:
  # Posts default settings
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      comments: false
      # Include in sitemap
      sitemap: true

  # Projects settings
  - scope:
      type: projects
    values:
      seo:
        type: WebPage

  # Featured categories settings
  - scope:
      type: featured_categories
    values:
      seo:
        type: WebPage

  # Featured tags settings
  - scope:
      type: featured_tags
    values:
      seo:
        type: WebPage

  # Exclude assets folder from sitemap
  - scope:
      path: assets/
    values:
      sitemap: false

  # Exclude license pages from sitemap
  - scope:
      path: licenses/
    values:
      layout: plain
      sitemap: false

# Plugins
# ----------------------------------------------------------------------------------------
plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at

# Hydejack settings
# ----------------------------------------------------------------------------------------
hydejack:
  # Order of additional content to be displayed in posts
  post_addons: [about, newsletter, related, random, comments]
  
  # Order of additional content to be displayed in projects
  project_addons: [about, newsletter, other, comments]
  
  # Default settings
  no_mark_external: false
  no_push_state: false
  no_drawer: false
  no_navbar: false
  no_search: false
  no_inline_css: false
  no_page_style: false
  no_break_layout: true
  no_toc: false
  no_third_column: false
  no_large_headings: false
  no_structured_data: false
  no_theme_color: false
  no_breadcrumbs: false
  use_lsi: true
  cookies_banner: false
  advertise: false
  hide_dates: false
  hide_last_modified: false
  
  # Dark mode settings
  dark_mode:
    always: false
    dynamic: true
    icon: true

  # Offline settings (optional)
  offline:
    enabled: false
    cache_version: 13
    precache_assets:
      - /assets/img/swipe.svg

# File inclusion/exclusion
# ----------------------------------------------------------------------------------------
exclude:
  - ./#jekyll-theme-hydejack/node_modules
  - ./#jekyll-theme-hydejack/assets
  - ./#jekyll-theme-hydejack/.git
  - .jekyll-cache
  - .sass-cache
  - .ruby-lsp
  - .wrangler
  - '*.toml'
  - vendor
  - Gemfile
  - Gemfile.lock
  - functions

include:
  - _routes.json
  - .well-known
  - LICENSE.md

# Plugin settings
# ---------------------------------------------------------------------------------------
optional_front_matter:
  remove_originals: true

readme_index:
  remove_originals: true
  with_frontmatter: true

relative_links:
  collections: true

titles_from_headings:
  strip_title: true
  collections: true

compress_html:
  comments: ["<!--", "-->"]
  clippings: all
  endings: all
  ignore:
    envs: [development]

sass:
  style: compressed

# Jekyll Compose defaults (for creating new posts)
# ---------------------------------------------------------------------------------------
jekyll_compose:
  default_front_matter:
    drafts:
      layout: post
      description: > 
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
    posts:
      layout: post
      description: > 
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
    projects:
      layout: project
      description: > 
        A short ~160 character description of your post for search engines,
        social media previews, etc.
      image:
        path: /assets/img/sidebar-bg.jpg
      links:
        - title: Project Link
          url: https://example.com
